# Agent Queue 'Azure Pipelines' was used with unrecognized Agent Specification, vmImage property must be specified to determine image - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
trigger:
  branches:
    include:
    - refs/heads/main
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Azure Pipelines
  steps:
  - checkout: self
    clean: False
  - task: Docker@0
    displayName: Build an image
    inputs:
      azureSubscriptionEndpoint: 31bd2fa2-884e-411a-97b0-33a39a546bf9
      azureContainerRegistry: '{"loginServer":"toccservices.azurecr.io", "id" : "/subscriptions/8b92cc1d-f180-44d7-8d1b-9453a8e792cc/resourceGroups/rg-weu-shared-tocc-mscb-dev-and-test/providers/Microsoft.ContainerRegistry/registries/toccservices"}'
      dockerFile: Dockerfile
      buildArguments: environment=prod
      imageName: softwareservice:$(Build.BuildId)
  - task: Bash@3
    displayName: Copy Artifacts
    inputs:
      targetType: inline
      script: >-
        export imageid=$(docker images toccservices.azurecr.io/softwareservice -q)

        docker create --name unittestcontainer $imageid


        docker cp unittestcontainer:/app/testresults ./testresults

        docker cp unittestcontainer:/app/efbundle ./SoftwareService/efbundle


        docker stop unittestcontainer

        docker rm unittestcontainer
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/softwareservicetestresults.xml'
      searchFolder: $(System.DefaultWorkingDirectory)/testresults
  - task: PublishCodeCoverageResults@2
    displayName: Publish code coverage results
    inputs:
      summaryFileLocation: $(System.DefaultWorkingDirectory)/testresults/coverage/coverage.cobertura.xml
  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@9
    displayName: Check build quality Line Coverage
    enabled: False
    inputs:
      checkWarnings: true
      warningFailOption: fixed
      warningThreshold: 3
      checkCoverage: true
      coverageFailOption: fixed
      coverageType: lines
      coverageThreshold: 70
  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@9
    displayName: Check build quality
    inputs:
      checkWarnings: true
      warningFailOption: fixed
      warningThreshold: 3
      coverageType: lines
      coveragePrecision: 70
  - task: mspremier.BuildQualityChecks.QualityChecks-task.BuildQualityChecks@8
    displayName: Check build quality Branch Coverage
    enabled: False
    inputs:
      checkWarnings: true
      warningFailOption: fixed
      warningThreshold: 1
      checkCoverage: true
      coverageFailOption: fixed
      coverageType: branches
      coverageThreshold: 50
  - task: Docker@0
    displayName: Push an image
    inputs:
      azureSubscriptionEndpoint: 31bd2fa2-884e-411a-97b0-33a39a546bf9
      azureContainerRegistry: '{"loginServer":"toccservices.azurecr.io", "id" : "/subscriptions/8b92cc1d-f180-44d7-8d1b-9453a8e792cc/resourceGroups/rg-weu-shared-tocc-mscb-dev-and-test/providers/Microsoft.ContainerRegistry/registries/toccservices"}'
      action: Push an image
      imageName: softwareservice:$(Build.BuildId)
  - task: CopyFiles@2
    displayName: Copy Deployment Files
    inputs:
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...
